db_path_train: /home/chris/nsync_dump/train
db_path_test: /home/chris/nsync_dump/test
db_path_valid: /home/chris/nsync_dump/valid
random_seed: ${RANDOM_SEED}
num_workers: 0
pitch: [53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]

defaults:
  - vae: vae