db_path_train: data/processed/train
db_path_valid: data/processed/valid
db_path_test: data/processed/test
random_seed: ${RANDOM_SEED}
num_workers: 0
pitch: -1

defaults:
  - vae: vae
  - transformer: transformer