db_path_train: data/processed/train
db_path_test: data/processed/test
db_path_valid: data/processed/valid
random_seed: ${RANDOM_SEED}
batch_size: 32
num_workers: 0
pitch: [53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]

defaults:
  - vae: vae