stages:
  preprocess:
    cmd: python source/preprocess.py
    deps:
    - source/preprocess.py
    - data/raw/
    params:
    - preprocess
    outs:
    - data/processed/
  # train_vae:
  #   cmd: python source/train_vae.py
  #   deps:
  #   - source/train_vae.py
  #   - source/vae.py
  #   - data/processed/
  #   params:
  #   - train
  #   outs:
  #   - models/checkpoints/
  # export:
  #   cmd: python source/export.py
  #   deps:
  #   - source/export.py
  #   - models/checkpoints/
  #   params:
  #   - general.input_size
  #   outs:
  #   - models/exports/
  # save_logs:
  #   cmd: python source/utils/logs.py
  #   deps:
  #   - source/utils/logs.py
  #   outs:
  #   - exp_logs/
