stages:
  # python -u, for unbuffered output as hpc prints slowly otherwise
  preprocess:
    cmd: python -u source/preprocess.py
    deps:
    - data/raw/
    - source/preprocess.py
    params:
    - preprocess
    outs:
    - data/processed/
    frozen: true
  train_vae:
    cmd: python -u source/train_vae.py
    deps:
    - source/train_vae.py
    - source/vae.py
    # - data/processed/ # Takes to long to hash
    params:
    - train
    outs:
    - out/
  # export:
  #   cmd: python source/export.py
  #   deps:
  #   - source/export.py
  #   - models/checkpoints/
  #   params:
  #   - general.input_size
  #   outs:
  #   - models/exports/
  # save_logs:
  #   cmd: python source/utils/logs.py
  #   deps:
  #   - source/utils/logs.py
  #   outs:
  #   - exp_logs/
