preprocess:
  input_path_train: data/raw/nsynth-train
  output_path_train: data/processed/train
  input_path_valid: data/raw/nsynth-valid
  output_path_valid: data/processed/valid
  input_path_test: data/raw/nsynth-test
  output_path_test: data/processed/test
  model_name: facebook/encodec_24khz
  sample_rate: 24000
  initial_db_size: 1
  db_writemap: false
  ext:
  - wav
  num_workers: 30
  batch_size: 8
train:
  vae:
    epochs: 500
    batch_size: 1024
    lr: 0.0001
    wd: 0.05
    betas:
    - 0.9
    - 0.95
    dropout_ratio: 0.0
    eval_interval: 5
    visualize_interval: 10
    hear_interval: 10
    save_interval: 20
    input_crop: 150
    channels:
    - 128
    - 256
    - 512
    - 1024
    - 2048
    - 4096
    linears:
    - 16384
    - 8192
    - 4096
    - 2048
    - 1024
    - 512
    - 2
    calculate_vae_loss:
      _target_: vae.calculate_vae_loss
      _partial_: true
      num_epochs: 500
      weighted_reproduction: false
      loss_fn:
        _target_: torch.nn.MSELoss
        reduction: sum
      cls_loss_fn:
        _target_: torch.nn.CrossEntropyLoss
      batch_size: 1024
  transformer:
    epochs: 2000
    learning_rate: 0.0001
    weight_decay: 0.05
    betas:
    - 0.9
    - 0.95
    batch_size: 256
    eval_interval: 200
    visualize_interval: 200
    hear_interval: 200
    save_interval: 1000
    block_size: 300
    input_dimension: 128
    internal_dimension: 512
    feedforward_dimension: 2048
    n_layer_encoder: 8
    n_layer_decoder: 11
    n_head: 8
    dropout: 0.0
    condition_model_path: out/vae/checkpoints/vae_final_epoch_150.torch
    loss_fn:
      _target_: torch.nn.MSELoss
      reduction: mean
  db_path_train: data/processed/train
  db_path_valid: data/processed/valid
  db_path_test: data/processed/test
  random_seed: 42
  num_workers: 30
  pitch: -1
  device: auto
SAMPLING_RATE: 24000
RANDOM_SEED: 42
