preprocess:
  input_path_train: data/raw/nsynth-train
  output_path_train: data/processed/train
  input_path_valid: data/raw/nsynth-valid
  output_path_valid: data/processed/valid
  input_path_test: data/raw/nsynth-test
  output_path_test: data/processed/test
  model_name: facebook/encodec_24khz
  sample_rate: 24000
  max_db_size: 10
  ext:
  - wav
train:
  db_path_valid: data/processed/valid
  random_seed: 42
  batch_size: 32
  num_workers: 8
  pitch:
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
SAMPLING_RATE: 24000
RANDOM_SEED: 42
device: cuda
