preprocess:
  input_path_train: data/raw/nsynth-train
  output_path_train: data/processed/train
  input_path_valid: data/raw/nsynth-valid
  output_path_valid: data/processed/valid
  input_path_test: data/raw/nsynth-test
  output_path_test: data/processed/test
  model_name: facebook/encodec_24khz
  sample_rate: 24000
  initial_db_size: 1
  db_writemap: false
  ext:
  - wav
  num_workers: 30
  batch_size: 8
train:
  vae:
    epochs: 150
    batch_size: 512
    lr: 0.0001
    wd: 0.05
    betas:
    - 0.9
    - 0.95
    dropout_ratio: 0.2
    eval_interval: 5
    visualize_interval: 25
    hear_interval: 25
    save_interval: 50
    input_crop: 150
    channels:
    - 128
    - 256
    - 512
    - 1024
    - 2048
    - 4096
    linears:
    - 16384
    - 8192
    - 4096
    - 2048
    - 1024
    - 512
    - 2
    calculate_vae_loss:
      _target_: vae.calculate_vae_loss
      _partial_: true
      epochs: 150
      weighted_reproduction: false
      loss_fn:
        _target_: torch.nn.MSELoss
        reduction: sum
      cls_loss_fn:
        _target_: torch.nn.CrossEntropyLoss
      batch_size: 512
  db_path_train: data/processed/train
  db_path_valid: data/processed/valid
  db_path_test: data/processed/test
  random_seed: 42
  num_workers: 0
  pitch: -1
SAMPLING_RATE: 24000
RANDOM_SEED: 42
device: cuda
