RANDOM_SEED: 42
SAMPLING_RATE: 24000
device: cuda
preprocess:
  batch_size: 64
  ext:
  - wav
  input_path_test: data/raw/nsynth-test
  input_path_train: data/raw/nsynth-train
  input_path_valid: data/raw/nsynth-valid
  max_db_size: 10
  model_name: facebook/encodec_24khz
  num_workers: 8
  output_path_test: data/processed/test
  output_path_train: data/processed/train
  output_path_valid: data/processed/valid
  sample_rate: 24000
train:
  batch_size: 32
  db_path_test: data/processed/test
  db_path_train: data/processed/train
  db_path_valid: data/processed/valid
  num_workers: 0
  pitch:
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
  random_seed: 42
  vae:
    batch_size: 1024
    betas:
    - 0.9
    - 0.95
    calculate_vae_loss:
      _partial_: true
      _target_: vae.calculate_vae_loss
      batch_size: 1024
      epochs: 1000
      loss_fn:
        _target_: torch.nn.MSELoss
        reduction: sum
      weighted_reproduction: true
    channels:
    - 128
    - 256
    - 128
    - 64
    epochs: 1000
    input_crop: 150
    linears:
    - 256
    - 128
    - 64
    - 32
    - 2
    lr: 0.0006
    wd: 0.05
