preprocess:
  input_path_valid: data/raw/nsynth-valid
  output_path_valid: data/processed/valid
  model_name: facebook/encodec_24khz
  sample_rate: 24000
  max_db_size: 10
  ext:
  - wav
train:
  vae:
    epochs: 1000
    batch_size: 1024
    lr: 0.0006
    wd: 0.05
    betas:
    - 0.9
    - 0.95
    weighted_reproduction: false
    input_crop: 150
    channels:
    - 128
    - 256
    - 128
    - 64
    linears:
    - 256
    - 128
    - 64
    - 32
    - 2
    calculate_vae_loss:
      _target_: vae.calculate_vae_loss
      _partial_: true
      epochs: 1000
      weighted_reproduction: false
      loss_fn:
        _target_: torch.nn.MSELoss
        reduction: sum
      batch_size: 1024
  db_path_valid: data/processed/valid
  random_seed: 42
  batch_size: 32
  num_workers: 0
  pitch:
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
SAMPLING_RATE: 24000
RANDOM_SEED: 42
device: cuda
