preprocess:
  input_path_train: data/raw/nsynth-train
  output_path_train: data/processed/train
  input_path_valid: data/raw/nsynth-valid
  output_path_valid: data/processed/valid
  input_path_test: data/raw/nsynth-test
  output_path_test: data/processed/test
  model_name: facebook/encodec_24khz
  sample_rate: 24000
  initial_db_size: 1
  db_writemap: false
  ext:
  - wav
  num_workers: 30
  batch_size: 8
train:
  vae:
    epochs: 200
    batch_size: 256
    lr: 0.0001
    wd: 0.05
    betas:
    - 0.9
    - 0.95
    dropout_ratio: 0.0
    eval_interval: 5
    visualize_interval: 5
    hear_interval: 40
    save_interval: 5
    input_crop: 150
    channels:
    - 128
    - 256
    - 512
    - 1024
    - 2048
    linears:
    - 8192
    - 4096
    - 2048
    - 1024
    - 512
    - 2
    rec_beta: 0.2
    rep_beta: 0.5
    spa_beta: 1.0
    cla_beta: 0.12
    inst_beta: 0.07
    reg_scaling_exp: 2.0
    calculate_vae_loss:
      _target_: vae.calculate_vae_loss
      _partial_: true
      num_epochs: 200
      weighted_reproduction: false
      loss_fn:
        _target_: torch.nn.MSELoss
        reduction: sum
      cls_loss_fn:
        _target_: torch.nn.CrossEntropyLoss
      batch_size: 256
  transformer:
    epochs: 100
    batch_size: 128
    learning_rate: 0.0001
    weight_decay: 0.05
    betas:
    - 0.9
    - 0.95
    eval_interval: 5
    visualize_interval: 10
    hear_interval: 10
    save_interval: 25
    block_size: 300
    input_dimension: 128
    internal_dimension: 512
    feedforward_dimension: 2048
    n_layer_encoder: 8
    n_layer_decoder: 11
    n_head: 8
    dropout: 0.0
    condition_model_path: out/vae/checkpoints/vae_final_epoch_200.torch
    loss_fn:
      _target_: torch.nn.MSELoss
      reduction: mean
  db_path_train: data/processed/train
  db_path_valid: data/processed/valid
  db_path_test: data/processed/test
  random_seed: 42
  num_workers: 30
  pitch:
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
  - 72
  - 73
  - 74
  - 75
  - 76
  - 77
  - 78
  - 79
  - 80
  - 81
  - 82
  - 83
  - 84
  - 85
  - 86
  - 87
  - 88
  - 89
  - 90
  - 91
  - 92
  - 93
  - 94
  - 95
  - 96
  - 97
  - 98
  - 99
  - 100
  - 101
  - 102
  - 103
  - 104
  - 105
  - 106
  - 107
  - 108
  device: auto
  deterministic: true
SAMPLING_RATE: 24000
RANDOM_SEED: 42
