preprocess:
  input_path_train: data/raw/nsynth-train
  output_path_train: data/processed/train
  input_path_valid: data/raw/nsynth-valid
  output_path_valid: data/processed/valid
  input_path_test: data/raw/nsynth-test
  output_path_test: data/processed/test
  model_name: facebook/encodec_24khz
  sample_rate: 24000
  initial_db_size: 1
  db_writemap: false
  ext:
  - wav
  num_workers: 30
  batch_size: 8
train:
  vae:
    epochs: 15000
    batch_size: 256
    lr: 0.0003
    wd: 0.05
    betas:
    - 0.9
    - 0.95
    dropout_ratio: 0.1
    eval_interval: 50
    visualize_interval: 50
    hear_interval: 300
    save_interval: 1000
    input_crop: 150
    channels:
    - 128
    - 256
    - 512
    - 1024
    - 1024
    - 512
    linears:
    - 4096
    - 2048
    - 1024
    - 512
    - 2
    rec_beta: 0.8
    neighbor_beta: 1.0
    spa_beta: 0.1
    kl_beta: 0.006
    note_cls_beta: 0.12
    family_cls_beta: 0.07
    instrument_cls_beta: 0.007
    reg_scaling_exp_neighbor: 0.5
    reg_scaling_exp_family: 1.5
    reg_scaling_exp_instrument: 0.8
    calculate_vae_loss:
      _target_: vae.calculate_vae_loss
      _partial_: true
      num_epochs: 15000
      weighted_reproduction: false
      loss_fn:
        _target_: torch.nn.MSELoss
        reduction: sum
      cls_loss_fn:
        _target_: torch.nn.CrossEntropyLoss
      batch_size: 256
  transformer:
    epochs: 5000
    batch_size: 64
    learning_rate: 0.0001
    weight_decay: 0.05
    betas:
    - 0.9
    - 0.95
    eval_interval: 50
    visualize_interval: 50
    hear_interval: 500
    save_interval: 1000
    num_batches_evaluation: 20
    block_size: 300
    input_dimension: 128
    internal_dimension: 512
    feedforward_dimension: 8192
    n_layer_encoder: 8
    n_layer_decoder: 12
    n_head: 8
    dropout: 0.1
    std_multiplier: 0.0
    loss_fn:
      _target_: torch.nn.MSELoss
      reduction: mean
  db_path_train: data/processed/train
  db_path_valid: data/processed/valid
  db_path_test: data/processed/test
  random_seed: 42
  num_workers: 25
  pitch:
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
  - 72
  max_inst_per_family: 10
  velocity:
  - 100
  device: auto
  deterministic: true
  vae_path: out/vae/checkpoints/vae_final_timid-orfe_epoch_15000.torch
  transformer_path: out/transformer/checkpoints/transformer_final_hazel-shay_epoch_5000.torch
SAMPLING_RATE: 24000
RANDOM_SEED: 42
