RANDOM_SEED: 42
SAMPLING_RATE: 24000
preprocess:
  batch_size: 8
  db_writemap: false
  ext:
  - wav
  initial_db_size: 1
  input_path_test: data/raw/nsynth-test
  input_path_train: data/raw/nsynth-train
  input_path_valid: data/raw/nsynth-valid
  model_name: facebook/encodec_24khz
  num_workers: 30
  output_path_test: data/processed/test
  output_path_train: data/processed/train
  output_path_valid: data/processed/valid
  sample_rate: 24000
train:
  db_path_test: data/processed/test
  db_path_train: data/processed/train
  db_path_valid: data/processed/valid
  deterministic: true
  device: auto
  max_inst_per_family: 40
  num_workers: 0
  pitch:
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
  - 72
  random_seed: 42
  transformer:
    batch_size: 96
    betas:
    - 0.9
    - 0.95
    block_size: 300
    condition_model_path: out/vae/checkpoints/vae_final_epoch_1000.torch
    dropout: 0.1
    epochs: 5000
    eval_interval: 100
    feedforward_dimension: 2048
    hear_interval: 500
    input_dimension: 128
    internal_dimension: 512
    learning_rate: 0.0001
    loss_fn:
      _target_: torch.nn.MSELoss
      reduction: mean
    n_head: 8
    n_layer_decoder: 12
    n_layer_encoder: 8
    num_batches_evaluation: 5
    save_interval: 1000
    visualize_interval: 500
    weight_decay: 0.05
  transformer_path: out/transformer/checkpoints/transformer_final_epoch_5000.torch
  vae:
    batch_size: 256
    betas:
    - 0.9
    - 0.95
    calculate_vae_loss:
      _partial_: true
      _target_: vae.calculate_vae_loss
      batch_size: 256
      cls_loss_fn:
        _target_: torch.nn.CrossEntropyLoss
      loss_fn:
        _target_: torch.nn.MSELoss
        reduction: sum
      num_epochs: 3000
      weighted_reproduction: false
    channels:
    - 128
    - 256
    - 512
    - 1024
    - 2048
    cla_beta: 0.12
    dropout_ratio: 0.2
    epochs: 3000
    eval_interval: 50
    hear_interval: 300
    input_crop: 150
    inst_beta: 0.07
    linears:
    - 8192
    - 4096
    - 2048
    - 1024
    - 512
    - 2
    lr: 0.0001
    rec_beta: 0.2
    reg_scaling_exp: 2.0
    rep_beta: 0.6
    save_interval: 1000
    spa_beta: 1.0
    visualize_interval: 300
    wd: 0.05
  vae_path: out/vae/checkpoints/vae_final_epoch_3000.torch
  velocity:
  - 100
