epochs: 500
batch_size: 32
lr: 1e-4 # learning rate
wd: 0.05 # weight decay
betas: [0.9, 0.95] # adam betas
dropout_ratio: 0.0

# crop the time dimension to this length (150 -> input_crop)
input_crop: 150

# vae with convolutional layers
channels: [128, 256, 128, 64]
linears: [256, 128, 64, 32, 2]

calculate_vae_loss:
  _target_: vae.calculate_vae_loss
  _partial_: true
  epochs: ${train.vae.epochs}
  weighted_reproduction: false
  loss_fn:
    _target_: torch.nn.MSELoss
    reduction: sum
  batch_size: ${train.vae.batch_size}