epochs: 200
batch_size: 256
lr: 1e-4 # learning rate
wd: 0.05 # weight decay
betas: [0.9, 0.95] # adam betas
dropout_ratio: 0.
eval_interval: 5
visualize_interval: 10
hear_interval: 10
save_interval: 20

# crop the time dimension to this length (150 -> input_crop)
input_crop: 150

# vae with convolutional layers
channels: [128, 256, 512, 1024, 2048, 4096]
linears: [8192, 4096, 2048, 1024, 512, 2]

calculate_vae_loss:
  _target_: vae.calculate_vae_loss
  _partial_: true
  num_epochs: ${train.vae.epochs}
  weighted_reproduction: false
  loss_fn:
    _target_: torch.nn.MSELoss
    reduction: sum
  cls_loss_fn:
    _target_: torch.nn.CrossEntropyLoss
  batch_size: ${train.vae.batch_size}