input_path_train: data/raw/nsynth-train
output_path_train: data/processed/train
input_path_valid: data/raw/nsynth-valid
output_path_valid: data/processed/valid
input_path_test: data/raw/nsynth-test
output_path_test: data/processed/test
model_name: "facebook/encodec_24khz"
sample_rate: ${SAMPLING_RATE}
# Database size in GB
max_db_size_train: 80
max_db_size_valid: 10
max_db_size_test: 10
ext: ["wav"]
num_workers: 8  # Or the number of cores you want to use
batch_size: 1  # Adjust based on memory constraints
