# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta_audio_file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15meta_audio_file.proto\x12\x0fmeta_audio_file\"\xaa\x07\n\rMetaAudioFile\x12<\n\naudio_file\x18\x01 \x01(\x0b\x32(.meta_audio_file.MetaAudioFile.AudioFile\x12\x39\n\x08metadata\x18\x02 \x01(\x0b\x32\'.meta_audio_file.MetaAudioFile.MetaData\x1a\x96\x01\n\tAudioFile\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x03\x12;\n\tprecision\x18\x03 \x01(\x0e\x32(.meta_audio_file.MetaAudioFile.Precision\x12\x14\n\x0cnum_channels\x18\x04 \x01(\x03\x12\x13\n\x0bnum_samples\x18\x05 \x01(\x03\x1a\xcc\x03\n\x08MetaData\x12\x0c\n\x04note\x18\x01 \x01(\x03\x12\x12\n\ninstrument\x18\x02 \x01(\x03\x12\r\n\x05pitch\x18\x03 \x01(\x03\x12\x10\n\x08velocity\x18\x04 \x01(\x03\x12\x11\n\tqualities\x18\x05 \x03(\x03\x12H\n\x06\x66\x61mily\x18\x06 \x01(\x0e\x32\x38.meta_audio_file.MetaAudioFile.MetaData.InstrumentFamily\x12H\n\x06source\x18\x07 \x01(\x0e\x32\x38.meta_audio_file.MetaAudioFile.MetaData.InstrumentSource\"?\n\x10InstrumentSource\x12\x0c\n\x08\x41\x43OUSTIC\x10\x00\x12\x0e\n\nELECTRONIC\x10\x01\x12\r\n\tSYNTHETIC\x10\x02\"\x94\x01\n\x10InstrumentFamily\x12\x08\n\x04\x42\x41SS\x10\x00\x12\t\n\x05\x42RASS\x10\x01\x12\t\n\x05\x46LUTE\x10\x02\x12\n\n\x06GUITAR\x10\x03\x12\x0c\n\x08KEYBOARD\x10\x04\x12\n\n\x06MALLET\x10\x05\x12\t\n\x05ORGAN\x10\x06\x12\x08\n\x04REED\x10\x07\x12\n\n\x06STRING\x10\x08\x12\x0e\n\nSYNTH_LEAD\x10\t\x12\t\n\x05VOCAL\x10\n\x1a\x66\n\nEmbeddings\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12;\n\tprecision\x18\x02 \x01(\x0e\x32(.meta_audio_file.MetaAudioFile.Precision\x12\r\n\x05shape\x18\x03 \x03(\x03\"P\n\tPrecision\x12\x08\n\x04INT8\x10\x00\x12\t\n\x05INT16\x10\x01\x12\t\n\x05INT32\x10\x02\x12\t\n\x05INT64\x10\x03\x12\x0b\n\x07\x46LOAT32\x10\x04\x12\x0b\n\x07\x46LOAT64\x10\x05\x62\x06proto3')



_METAAUDIOFILE = DESCRIPTOR.message_types_by_name['MetaAudioFile']
_METAAUDIOFILE_AUDIOFILE = _METAAUDIOFILE.nested_types_by_name['AudioFile']
_METAAUDIOFILE_METADATA = _METAAUDIOFILE.nested_types_by_name['MetaData']
_METAAUDIOFILE_EMBEDDINGS = _METAAUDIOFILE.nested_types_by_name['Embeddings']
_METAAUDIOFILE_METADATA_INSTRUMENTSOURCE = _METAAUDIOFILE_METADATA.enum_types_by_name['InstrumentSource']
_METAAUDIOFILE_METADATA_INSTRUMENTFAMILY = _METAAUDIOFILE_METADATA.enum_types_by_name['InstrumentFamily']
_METAAUDIOFILE_PRECISION = _METAAUDIOFILE.enum_types_by_name['Precision']
MetaAudioFile = _reflection.GeneratedProtocolMessageType('MetaAudioFile', (_message.Message,), {

  'AudioFile' : _reflection.GeneratedProtocolMessageType('AudioFile', (_message.Message,), {
    'DESCRIPTOR' : _METAAUDIOFILE_AUDIOFILE,
    '__module__' : 'meta_audio_file_pb2'
    # @@protoc_insertion_point(class_scope:meta_audio_file.MetaAudioFile.AudioFile)
    })
  ,

  'MetaData' : _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), {
    'DESCRIPTOR' : _METAAUDIOFILE_METADATA,
    '__module__' : 'meta_audio_file_pb2'
    # @@protoc_insertion_point(class_scope:meta_audio_file.MetaAudioFile.MetaData)
    })
  ,

  'Embeddings' : _reflection.GeneratedProtocolMessageType('Embeddings', (_message.Message,), {
    'DESCRIPTOR' : _METAAUDIOFILE_EMBEDDINGS,
    '__module__' : 'meta_audio_file_pb2'
    # @@protoc_insertion_point(class_scope:meta_audio_file.MetaAudioFile.Embeddings)
    })
  ,
  'DESCRIPTOR' : _METAAUDIOFILE,
  '__module__' : 'meta_audio_file_pb2'
  # @@protoc_insertion_point(class_scope:meta_audio_file.MetaAudioFile)
  })
_sym_db.RegisterMessage(MetaAudioFile)
_sym_db.RegisterMessage(MetaAudioFile.AudioFile)
_sym_db.RegisterMessage(MetaAudioFile.MetaData)
_sym_db.RegisterMessage(MetaAudioFile.Embeddings)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METAAUDIOFILE._serialized_start=43
  _METAAUDIOFILE._serialized_end=981
  _METAAUDIOFILE_AUDIOFILE._serialized_start=182
  _METAAUDIOFILE_AUDIOFILE._serialized_end=332
  _METAAUDIOFILE_METADATA._serialized_start=335
  _METAAUDIOFILE_METADATA._serialized_end=795
  _METAAUDIOFILE_METADATA_INSTRUMENTSOURCE._serialized_start=581
  _METAAUDIOFILE_METADATA_INSTRUMENTSOURCE._serialized_end=644
  _METAAUDIOFILE_METADATA_INSTRUMENTFAMILY._serialized_start=647
  _METAAUDIOFILE_METADATA_INSTRUMENTFAMILY._serialized_end=795
  _METAAUDIOFILE_EMBEDDINGS._serialized_start=797
  _METAAUDIOFILE_EMBEDDINGS._serialized_end=899
  _METAAUDIOFILE_PRECISION._serialized_start=901
  _METAAUDIOFILE_PRECISION._serialized_end=981
# @@protoc_insertion_point(module_scope)
